version: "3.9"

services:
  database:
    container_name: postgres-prod
    image: postgres:17.0
    env_file:
      - ../.env.production
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  web:
    container_name: django-ninja-prod
    build:
      context: ..
      dockerfile: infra/Dockerfile-pro
    env_file:
      - ../.env.production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.myapi.rule=Host(`myapi.brunononogaki.com`)"
      - "traefik.http.routers.myapi.entrypoints=websecure"
      - "traefik.http.routers.myapi.tls=true"
      - "traefik.http.services.myapi.loadbalancer.server.port=8000"
      - "traefik.docker.network=my-network"
    networks:
      - my-network
    depends_on:
      - database
    restart: unless-stopped
    volumes:
      - ../:/app
    environment:
      - DJANGO_SETTINGS_MODULE=myapi.settings
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  pgdata:

networks:
  my-network:
    external: true
