FROM python:3.13-slim


# Install system dependencies
RUN apt-get update && apt-get install -y build-essential libpq-dev && rm -rf /var/lib/apt/lists/*

WORKDIR /app


 # Copy only dependency files for faster cache install
COPY pyproject.toml poetry.lock ./
RUN pip install --no-cache-dir poetry && poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi --only main

# Copy the rest of the code
COPY . .

# Expose Uvicorn port
EXPOSE 8000

# Default command (can be overridden in docker-compose)
CMD ["uvicorn", "myapi.asgi:application", "--host", "0.0.0.0", "--port", "8000"]