# Generated by Django 5.2.8 on 2026-05-21 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshTokenDenylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.UUIDField(db_index=True, unique=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['expires_at'], name='core_refres_expires_61b017_idx')],
            },
        ),
    ]
