# Generated by Django 5.2.8 on 2025-12-28 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UUIDUser',
        ),
    ]
