"""
Django settings for myapi project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from decouple import Csv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# Detectar automaticamente se é produção ou desenvolvimento
BACKEND_FQDN = config('BACKEND_FQDN', default='localhost:8000')
IS_PRODUCTION = 'localhost' not in BACKEND_FQDN.lower()

# Proxy reverso configuration (Traefik) - apenas em produção
if IS_PRODUCTION:
    USE_X_FORWARDED_HOST = True
    USE_X_FORWARDED_PROTO = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
else:
    USE_X_FORWARDED_HOST = False
    USE_X_FORWARDED_PROTO = False

# Security headers (dev + prod)
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
X_FRAME_OPTIONS = 'DENY'

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())

# CSRF Configuration
CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS', default='http://localhost:8000,http://127.0.0.1:8000', cast=Csv()
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # django-allauth
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    # custom apps
    'corsheaders',
    'django_extensions',
    'myapi.core',
    'myapi.users',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # CORS
    'corsheaders.middleware.CorsMiddleware',
    # Security headers extras
    'myapi.core.middleware.SecurityHeadersMiddleware',
]

ROOT_URLCONF = 'myapi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myapi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('POSTGRES_DB', default='postgres'),
        'USER': config('POSTGRES_USER', default='devuser'),
        'PASSWORD': config('POSTGRES_PASSWORD', default='devpassword'),
        'HOST': config('DATABASE_HOST', default='localhost'),
        'PORT': config('DATABASE_PORT', default='5432'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise configuration
WHITENOISE_AUTOREFRESH = DEBUG
WHITENOISE_USE_FINDERS = True
WHITENOISE_MIMETYPES = {
    '.woff2': 'font/woff2',
    '.woff': 'font/woff',
    '.ttf': 'font/ttf',
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'users.UUIDUser'

CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS', default='http://localhost:3000,http://127.0.0.1:3000', cast=Csv()
)

# Permitir credenciais (cookies) em requisições CORS
CORS_ALLOW_CREDENTIALS = True

# Cookie settings
# Em produção: COOKIE_SECURE=True (só envia cookies via HTTPS)
# Em produção: COOKIE_DOMAIN=.seudominio.com (ponto inicial para cobrir subdomínios)
COOKIE_SECURE = config('COOKIE_SECURE', default=False, cast=bool)
COOKIE_DOMAIN = config('COOKIE_DOMAIN', default=None)

# Email Configuration - Gmail via Django
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = config('GMAIL_EMAIL', default='')
EMAIL_HOST_PASSWORD = config('GMAIL_APP_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('GMAIL_EMAIL', default='')

# SITE_ID (required for allauth)
SITE_ID = 1

# django-allauth settings
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # traditional login
    'allauth.account.auth_backends.AuthenticationBackend',  # social login
]

# allauth config
SOCIALACCOUNT_AUTO_SIGNUP = True  # Cria conta automaticamente
ACCOUNT_EMAIL_REQUIRED = True  # Email obrigatório
ACCOUNT_USERNAME_REQUIRED = True  # Username obrigatório (será gerado automaticamente)
ACCOUNT_AUTHENTICATION_METHOD = 'email'  # Usa email para autenticar
ACCOUNT_EMAIL_VERIFICATION = 'none'  # Não requer verificação de email
ACCOUNT_USER_MODEL_EMAIL_FIELD = 'email'  # Define email como campo principal
ACCOUNT_USERNAME_BLACKLIST = []  # Remove restrições de username
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True  # Conecta automaticamente se email existir
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True  # Auto-conecta contas com mesmo email
SOCIALACCOUNT_LOGIN_ON_GET = True  # Pula a página de confirmação e vai direto pro Google!

# Adaptador customizado para gerar username automaticamente
SOCIALACCOUNT_ADAPTER = 'myapi.core.adapters.SocialAccountAdapter'

# Configurações de login
FRONTEND_FQDN = config('FRONTEND_FQDN', default='localhost:3000')
FRONTEND_PROTOCOL = 'https' if 'localhost' not in FRONTEND_FQDN else 'http'
LOGIN_REDIRECT_URL = f'{FRONTEND_PROTOCOL}://{FRONTEND_FQDN}/accounts/google/login/callback'
ACCOUNT_LOGOUT_REDIRECT_URL = f'{FRONTEND_PROTOCOL}://{FRONTEND_FQDN}/'

# Configurações dos providers sociais
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
    }
}
