version: "3.8"

services:
  frontend-dev:
    build:
      context: ..
      dockerfile: infra/Dockerfile-dev
    container_name: myfront-dev
    ports:
      - "3000:3000"
    volumes:
      - ../pages:/app/pages
      - ../public:/app/public
    command: npm run dev
    restart: unless-stopped
    env_file:
      - ../../.env.development
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
