version: "3.8"

services:
  frontend:
    build:
      context: ../myfront
      dockerfile: ../infra/Dockerfile-pro
    container_name: frontend-prod
    expose:
      - "3000"
    restart: unless-stopped
    networks:
      - my-network
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    env_file:
      - ../../.env.production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`react.brunononogaki.com`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
      - "traefik.docker.network=my-network"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  my-network:
    external: true
