site_name: Django Ninja Passo-A-Passo
repo_name: brunononogaki/django-ninja-boilerplate
repo_url: https://github.com/brunononogaki/django-ninja-boilerplate
nav:
  - Home: index.md
  - Setup Inicial:
      - 01. Criando o ambiente de desenvolvimento: 01_setup_inicial/01_Ambiente_Dev.md
      - 02. Configurando o Django: 01_setup_inicial/02_Configurando_Django.md
      - 03. Criando o endpoint de status: 01_setup_inicial/03_Endpoint_status.md
      - 04. Implementando CI/CD: 01_setup_inicial/04_Implementando_CI_CD.md
      - 05. Implementando Linting de commits: 01_setup_inicial/05_Commit_linting.md
      - 06. Padronizando Erros: 01_setup_inicial/06_Padronizando_Erros.md
  - Setup do Front-End (React):
      - 01. Iniciando um projeto React com Next.js: 02_setup_front/01_Iniciando_React.md
      - 02. Criando a página de status: 02_setup_front/02_Pagina_Status.md
  - Usuários e Autenticação:
      - 01. Fazendo o CRUD de Users: 03_usuarios_autenticacao/01_CRUD_de_Users.md
      - 02. Implementando a ativação de contas: 03_usuarios_autenticacao/02_Ativacao_de_contas.md
      - 03. Implementando autenticação e autorização: 03_usuarios_autenticacao/03_Autenticacao_e_Autorizacao.md
      - 04. Implementando a troca e reset de senha: 03_usuarios_autenticacao/04_Troca_e_Reset_Senha.md
      - 05. Integrando Gmail para envio de e-mails: 03_usuarios_autenticacao/05_Integrando_Gmail_Emails.md
  - Criando tela de login e cadastro:
      - 01. Preparando o Front: 04_frontend_login/01_Preparando_Front.md
      - 02. Criando a tela de login: 04_frontend_login/02_Tela_login.md
      - 03. Criando a tela de cadastro: 04_frontend_login/03_Tela_cadastro.md
      - 04. Criando a tela de ativação: 04_frontend_login/04_Tela_ativacao.md
      - 05. Criando a tela de edição de dados do usuário: 04_frontend_login/05_Tela_edicao_dados.md
      - 06. Criando a tela de reset de senha: 04_frontend_login/06_Tela_reset_senha.md
      - 07. Mudando a autenticação para evitar ataques de XSS: 04_frontend_login/07_Problema_de_XSS.md
      - 08. Configurando o Login do Google com django-allauth: 04_frontend_login/08_Configurando_Login_Google.md
      - 09. Exibindo o Avatar do Google no perfil: 04_frontend_login/09_Avatar_Google.md
  - Apêndice:
      - 01. Configurando o Traefik: Appendix/01_Configurando_o_Traefik.md
      - 02. Rate Limiting: Appendix/02_Rate_Limiting.md
      - 03. Headers de Segurança: Appendix/03_Headers_de_Seguranca.md
      - 04. Transferindo o Domínio para a Cloudflare: Appendix/04_Transferencia_Dominio_Cloudflare.md
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      primary: green
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  logo: img/docs-logo.png
  favicon: img/favicon.svg
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.expand
    - search.highlight
    - search.suggest

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
